name: blowfish_ecb
description: A Blowfish ECB codec implementation in pure Dart.
version: 0.1.0
homepage: https://github.com/hacker1024/blowfish_ecb.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.5
